### ISSUE TITLE
各タブのカウント表示ができること

### ISSUE THREAD

**Issue by sakku-14** [sakku-14/TodoApp#10]

**Comment by sakku-14** [comment]
TodoTabControllerView.todoCount()がWidgetを返すメソッドなら、StatelessWidgetとして切り出して良さそう
![スクリーンショット 2023-09-04 21 16 24](https://github.com/sakku-14/TodoApp/assets/65479630/3093b4ef-d34c-4c49-91d4-fee18807d935)

**Comment by atsuhirouehara** [comment]
[a4c0a72](https://github.com/sakku-14/TodoApp/commit/a4c0a7265336328d0b1d473459561176a169a6c3)
上記コミットにて https://github.com/sakku-14/TodoApp/issues/10#issuecomment-1705174776 の指摘修正しました！

**Comment by sakku-14** [comment]
LGTM🚀
