### ISSUE TITLE
アプリを起動した際にTodoリストを表示できること

### ISSUE THREAD

**Issue by atsuhirouehara** [sakku-14/TodoApp#12]

**Comment by atsuhirouehara** [comment]
@sakku-14 さん
アプリを落としてもローカルに保存できており、その上でアプリを起動するとローカルから取得して表示されるってことですか？

**Comment by sakku-14** [comment]
SQLiteのdbファイル配置パスはユーザーのアクセス権が無い以下とする
- Android
  - sqfliteのgetDatabasePathで取得できるパス
- iOS
  - path_providerのgetLibraryDirectoryで取得できるパス

参考リンク
- [【Flutter】sqfliteパッケージによるDBファイルの配置場所について、もう少し考えてみる](https://zenn.dev/beeeyan/articles/b9f1b42de9cb67)

**Comment by sakku-14** [comment]
DBはSQLiteを使用
データの初期化したい時は、デバッグ実行時にコンソールにDBファイルのパスが表示されるので、そちら削除してください。

**Comment by sakku-14** [comment]
本対応でTodoListProviderがNotifierProviderからAsyncNotifierProviderに変更してます
使い方と単体テストに変更があります。

#### 使い方
DBから値取得することになり、TodoListProviderのStateが非同期で更新されるようになった（biuld()の戻り値がFutureOrになってます）
Stateを更新中の時は値がnullになり、Loadingという状態を取得できる
また、State更新中にエラーが発生した際はError状態になり、その状態も取得できる
無事に更新できたらStateの値を参照できる

#### 単体テスト
以下と単体テストのコード参考（なんとか説明も可...）
https://qiita.com/Seo-4d696b75/items/eee020162d0537fdbc36
