### ISSUE TITLE
登録用モーダルボトムシートの「登録」押下時に、Todoを追加できること

### ISSUE THREAD

**Issue by atsuhirouehara** [sakku-14/TodoApp#17]

**Comment by sakku-14** [comment]
- [x] リポジトリはState不要なので、NotifierProviderではなく、Providerで実装で十分だと思います
※参考コードのUseCaseをRepositoryに置き換えて読んでください
```dart
part 'hoge_use_case.g.dart';

class HogeUseCase{
  HogeUseCase();

  void execute() {
    // ユースケースの処理
  }
}

@riverpod
HogeUseCase hogeUseCase(HogeUseCaseRef ref) {
  return HogeUseCase();
}
``` 
- [ ] TodoListRepositoryのclone()はFreezedのcopyWithやTodoのコンストラクタで十分かと思います
- [x] 細かいことなんですが、TodoListRepository.getTodoList()のメソッド名に全部のTodoを取得してるの意味も含めたほうがいいと思います。findAll()とかいいかなと思います。後に条件に一致した一部のTodoのリストを返すメソッドが必要になるかもなので

**Comment by atsuhirouehara** [comment]
https://github.com/sakku-14/TodoApp/issues/17#issuecomment-1705260010
上記リンクの指摘内容を上から同じ順番で以下の通り修正しました！
- [ ]  NotifierProviderからProviderへ変更  [c5c48d8](https://github.com/sakku-14/TodoApp/commit/c5c48d8c918ca671f109ed9909c9272387071fe8)
- [ ] 指摘2に関してですが、Cloneとメソッド名がついていますが、処理自体はTodoを生成しているだけでメソッドに切り出しているような形になっているだけなのでそのまま残してもよろしいでしょうか。Cloneを呼び出しているところにTodoの生成処理を移すと、可読性が落ちてしまうので、Todoの生成メソッドとして切り出しているという状態にしておきたいです。
- [ ] Todoを全て取得する処理の名前をfindAllへ変更 [516917c](https://github.com/sakku-14/TodoApp/commit/516917cb59677f7e19f004cfd62b8ed27d2d9435)

**Comment by sakku-14** [comment]
> 指摘2に関してですが、Cloneとメソッド名がついていますが、処理自体はTodoを生成しているだけでメソッドに切り出しているような形になっているだけなのでそのまま残してもよろしいでしょうか。Cloneを呼び出しているところにTodoの生成処理を移すと、可読性が落ちてしまうので、Todoの生成メソッドとして切り出しているという状態にしておきたいです。

clone()使用してる箇所はすでにcopyWith()しているので、clone()呼び出し不要の箇所か、
copyWith()を呼べば良いかのどちらかだと思うので、不要な気がします
※copyWith()は引数なくても呼べるようです

**Comment by atsuhirouehara** [comment]
https://github.com/sakku-14/TodoApp/issues/17#issuecomment-1713857092 の指摘内容を [88bd760](https://github.com/sakku-14/TodoApp/commit/88bd760a19ded06e514e1181effe2274dedc74b4) こちらのコミットにて修正しました！

**Comment by sakku-14** [comment]
LGTM🚀

**Comment by sakku-14** [comment]
LGTM🚀
