### ISSUE TITLE
Stateを細分化し、複数Viewから参照することでEvent方式の同期方法から変更する

### ISSUE THREAD

**Issue by sakku-14** [sakku-14/TodoApp#24]
現状は、StateはViewが必要なStateは参照するViewModelに持たせている。
異なるViewでStateの同期を取る必要があれば、イベント発行し、同期するよう実装している。

riverpod使用したプロジェクト見ると、ViewModelという概念はなく、Stateをできるだけ細分化し、複数のViewから参照するように実装されてる。Pub/Subする必要ない仕組みになってるようです。（上原さんがイベント実装してくださってる真っ只中に知りました...）
コード量少なく、わかりやすい例があったので、参考コード載せておきます。
https://github.com/mono0926/wdb106-flutter

このTodoアプリでは、どっちにするのか決めたい。
現状のままのイベント方式で試しに実装していっても、State細分化して複数Viewから参照方式のどちらでもいいと思ってます。
※奥村さんのbaseアプリは後者ですw

**Comment by atsuhirouehara** [comment]
https://github.com/sakku-14/TodoApp/pull/27/files
プルリクにコメントしました！
指摘というよりは、疑問点を聞いてみたいな〜って感じで書いてみたんで、またゆっくり話せる時にでも教えてもらえればと思います！
