### ISSUE TITLE
IntegrationTest

### ISSUE THREAD

**Issue by atsuhirouehara** [sakku-14/TodoApp#30]
- [ ] 全てのタブからTodoを追加できること
- [ ] 全てのタブからTodoを編集できること
- [ ] Todo編集アイコンからステータスを変更した場合、対応したタブに移動されること
- [ ] DDからステータスを変更した場合、対応したタブに移動されること
- [ ] Todo削除アイコン押下後、確認ダイアログでOKを押下した場合、削除されること
- [ ] Todo削除アイコン押下後、確認ダイアログでCancelを押下した場合、削除されないこと
- [ ] 登録日時でソートできること
- [ ] 緊急度×重要度でソートできること
- [ ] 緊急度×重要度の結果が等しい場合、緊急度が優先されてソートできること
- [ ] 緊急度×重要度の結果、及び各ポイントも等しい場合、登録日時が優先されてソートできること

**Comment by sakku-14** [comment]
今回ここまで細かくやるのか(?)...と思って書いてるのもあります！
一応提案レベルで以下あげておきますw

- [ ] アプリ起動時、DBに保存されているTodoが表示できること
- [ ] 各タブに表示されているTodoの数をタブに表示できること
- [ ] Todo編集アイコンからTodoのタイトルや緊急度、重要度、ステータスを変更した後、キャンセルを押下すると元のTodoが更新されていないこと
- [ ] Todoの登録ボトムシートでタイトルを入力していない状態で登録ボタンを押下できないこと
- [ ] Todoの更新ボトムシートでタイトルをクリアした状態で更新ボタンを押下できないこと
- [ ] Todoの更新ボトムシート表示時、既存のTodoの内容を表示していること

**Comment by sakku-14** [comment]
ロボットテストの実装（実装開始前にやるクラスにチェックつけてください）
- [x] ModalBottomSheetRobot
- [x] TodoPaneRobot
- [x] MainScreenRobot

**Comment by sakku-14** [comment]
結合項目の整理
#### 登録
- [x] 全てのタブからTodoを追加できること
#### 変更
- [x] 全てのタブからTodoを編集できること
- [x] Todo編集アイコンからステータスを変更した場合、対応したタブに移動すること
- [x] DDからステータスを変更した場合、対応したタブに移動すること
- [x] Todo編集アイコンからTodoのタイトルや緊急度、重要度、ステータスを変更した後、キャンセルを押下するとTodoが元のまま更新されていないこと
- [x] Todoの登録ボトムシートでタイトルを入力していない状態で登録ボタンを押下できないこと
- [x] Todoの更新ボトムシートでタイトルをクリアした状態で更新ボタンを押下できないこと
- [x] Todoの更新ボトムシート表示時、既存のTodoの内容を表示していること
#### 削除
- [x] Todo削除アイコン押下後、確認ダイアログでOKを押下した場合、削除されること
- [x] Todo削除アイコン押下後、確認ダイアログでCancelを押下した場合、削除されないこと
#### 表示
- [x] 登録日時でソートできること
- [x] 緊急度×重要度でソートできること
  - [x] 緊急度×重要度の結果が等しい場合、緊急度が優先されてソートできること
  - [x] 緊急度×重要度の結果、及び各ポイントも等しい場合、登録日時が優先されてソートできること
- [x] 各タブに表示されているTodoの数をタブに表示できること
- [ ] アプリ起動時、DBに保存されているTodoが表示できること

**Comment by sakku-14** [comment]
DBある状態のテストで確認したいこと
- [x] タブに期待通りの個数のTodoが存在すること
- [x] Todoの表示が期待通りであること


DBない状態のテストで確認漏れ
- 登録、変更後
- [x] Todoの表示が期待通りであること
